[package]
name = "rust-dojo"
version = "0.1.0"
authors = ["Sergii <sergii.salata@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.11"
tokio = "1.4.0"