name: Create HotFix

on: 
  pull_request_target:
    types: [opened]
    branches:
    - 'fix/*'

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: 
        destination_branch: "develop"
        github_token: ${{ secrets.GITHUB_TOKEN }}