name: Manual => Create Release

on: 
  workflow_dispatch:
    inputs:
      major-version:
        description: 'Major version of release, e.g. 1.0 for 1.0.* releases'
        default: '1.0'
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: develop    
        fetch-depth: 0
    - run: |
        git fetch --tags
        git fetch --no-tags origin master
        VERSION=`git describe --match "${{ github.event.inputs.major-version }}.[0-9]*" --abbrev=0 --tags || echo "${{ github.event.inputs.major-version }}.0"`
        VERSION_BITS=(${VERSION//./ })
        VNUM1=${VERSION_BITS[0]}
        VNUM2=${VERSION_BITS[1]}
        VNUM3=${VERSION_BITS[2]}
        VNUM3=$((VNUM3+1))
        VERSION="$VNUM1.$VNUM2.$VNUM3"
        echo "::set-output name=version::$VERSION"
        git checkout develop
        git checkout -b release/$VERSION
        git config --global user.name "GitHub Action"
        git config --global user.email "github-action@users.noreply.github.com"
        git merge origin/master
        git push --set-upstream origin release/$VERSION
      id: release-branch
    - name: pull-request
      uses: repo-sync/pull-request@v2  
      with:
        pr_title: "Release ${{ steps.release-branch.outputs.version }}"
        source_branch: release/${{ steps.release-branch.outputs.version }}
        destination_branch: "master"
        github_token: ${{ secrets.GITHUB_TOKEN }}